name: Setup Enviroment
desription: Checkout, Setups Haskell and Stack, install Dependencies

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: setup stack config

    - name: Setup Haskell
      uses: haskell/actions/setup@v1.2
      with:
        enable-stack: true

    - name: Install dependencies
      run: |
        stack build --fast --skip-ghc-check --no-terminal --test --only-dependencies

    - name: Build
      run: |
        stack test --fast --bench --no-run-benchmarks --haddock --no-haddock-deps
